---
apiVersion: v1
kind: Pod
metadata:
  name: chaincodeinstall
spec:
  restartPolicy: "Never"
  volumes:
  - name: shared
    persistentVolumeClaim:
      claimName: shared-pvc
  containers:
  - name: chaincodeinstall
    image: ibmblockchain/fabric-tools:1.0.3
    imagePullPolicy: Always
    command: ["sh", "-c", "git clone -b v1.0.3 https://github.com/hyperledger/fabric $GOPATH/src/github.com/hyperledger/fabric/ && peer chaincode install -n ${CHAINCODE_NAME} -v ${CHAINCODE_VERSION} -p github.com/hyperledger/fabric/examples/chaincode/go/chaincode_example02/"]
    env:
    - name: CHAINCODE_NAME
      value: example02
    - name: CHAINCODE_VERSION
      value: "v1"
    - name: FABRIC_CFG_PATH
      value: /etc/hyperledger/fabric
    - name: CORE_PEER_MSPCONFIGPATH
      value: /shared/crypto-config/peerOrganizations/org2.example.com/users/Admin@org2.example.com/msp
    - name: CORE_PEER_LOCALMSPID
      value: Org2MSP
    - name: CORE_PEER_ADDRESS
      value: blockchain-org2peer1:30210
    - name: GODEBUG
      value: "netdns=go"
    volumeMounts:
    - mountPath: /shared
      name: shared
