---
apiVersion: v1
kind: Pod
metadata:
  name: chaincodeinstall
spec:
  restartPolicy: "Never"
  volumes:
  - name: shared
    persistentVolumeClaim:
      claimName: shared-pvc
  containers:
  - name: chaincodeinstall
    image: ibmblockchain/fabric-tools:1.1.0
    imagePullPolicy: Always
    command: ["sh", "-c", "git clone -b v1.1.0 https://github.com/hyperledger/fabric $GOPATH/src/github.com/hyperledger/fabric/ && peer chaincode install -n ${CHAINCODE_NAME} -v ${CHAINCODE_VERSION} -p github.com/hyperledger/fabric/examples/chaincode/go/chaincode_example02/"]
    env:
    - name: CHAINCODE_NAME
      value: DoesntMatter
    - name: CHAINCODE_VERSION
      value: "DoesntMatter"
    - name: FABRIC_CFG_PATH
      value: /etc/hyperledger/fabric
    - name: CORE_PEER_MSPCONFIGPATH
      value: DoesntMatter
    - name: CORE_PEER_LOCALMSPID
      value: DoesntMatter
    - name: CORE_PEER_ADDRESS
      value: DoesntMatter
    - name: GODEBUG
      value: "netdns=go"
    volumeMounts:
    - mountPath: /shared
      name: shared
